### PR TITLE
Level 1 Polish

### PR DESCRIPTION
**Pull request by tbuffard**
Please give me feedback on what you think I should change about the first level.

(Also I committed the input manager before you told us not to sorry Robin)

### CODE REVIEW

**Comment by filrod** [comment]
I fixed the bug for no passing zones reviving you. Turns out I check is something (what I thought would be an alive bok choy) is in the beta plane where you are. This found the trigger collider for some reason. It's fixed now.

**Comment by filrod** [comment]
Another issue is assuring all elements of the scene are placed correctly in the z axis (the end of level button could not be pressed and some bottles like this one also suffer from this issue.

image

the latter keep's the player from jumping

**Comment by filrod** [comment]
also watch out not to make objects too small
image

**Comment by filrod** [comment]
This was a needle in a haystack, please play the level extensively. We need to be careful with these bugs; rogue colliders are hard to find
image

**Comment by tbuffard** [comment]
> also watch out not to make objects too small
> image

> This was a needle in a haystack, please play the level extensively. We need to be careful with these bugs; rogue colliders are hard to find
> image

Not sure what you mean in either of these. Can you be more descriptive?

**Comment by filrod** [comment]
> > also watch out not to make objects too small
> > image
> 
> > This was a needle in a haystack, please play the level extensively. We need to be careful with these bugs; rogue colliders are hard to find
> > image
> 
> Not sure what you mean in either of these. Can you be more descriptive?

Sure, the first one I fixed by raycasting from the centre as well. The issue was that those raycasts, the blue lines were not hitting the vyle at the place where the bokchoy's feet are. We mentionned the potential for issues when raycasting only on the edges of the players collider and having surfaces that are smaller in diameter to the bok choy's collider was one of them.
I raycast from the centre now as well so it won't be an issue.

The other one was a random collider in the scene called gameobject and attached to the book as a child. It's well away from the book's mesh and was causing players to collide mid-air I therefore took it out. We need to be careful about this last issue since they are hard to spot and find. I have some commented out code in respawn's OnCollisionEnter method to tell you the name of the object you are colliding with.

**Pull request merged**
