### PR TITLE
Level 1 fixes

### PR DESCRIPTION
**Pull request by tbuffard**
Thumbtacks and some texture fixes.

### CODE REVIEW

**Comment by filrod** [comment]
All works, except this section but I believe it was like that in the previous version of the master branch:

Picture: Broken section, we die when we jump down here (it's lower than the respawn height)
image

**Comment by filrod** [comment]
What did you change for the lighting? It's very different and there are more lights now than ever before, one of which we should only turn on near the end. The glass material seems to have reduced in quality as well

**Comment by tbuffard** [comment]
> What did you change for the lighting? It's very different and there are more lights now than ever before, one of which we should only turn on near the end. The glass material seems to have reduced in quality as well

I just made it less green since the green of the skybox was washing out all the other colors. I added more lights because the map is longer and it wasn't well lit before. I'm not sure what you mean about the glass texture, could you be more descriptive? 



> All works, except this section but I believe it was like that in the previous version of the master branch:
> 
> Picture: Broken section, we die when we jump down here (it's lower than the respawn height)
> image

This is level 2. I've only changed level 1 in this pull request.

**Comment by filrod** [comment]
I fixed the skybox, it had it's direction light turned off. The glass material used on graduated cylinders had become matte so I put the sliders as they were on master. Everything is okay with me so I will confirm the merge.

**Pull request merged**
